import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import { Keypair, LAMPORTS_PER_SOL, PublicKey, SystemProgram } from "@solana/web3.js";
import { assert, expect } from "chai";
import { createHash } from "crypto";

// Anchor workspace import — generated by `anchor build` into target/types/.
// Until the program is built, this module won't exist; the path string keeps
// the editor quiet and ts-mocha will resolve it at runtime after a build.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const idl = require("../target/idl/silent_circle.json");
type SilentCircle = anchor.Idl;

const SESSION_SEED = Buffer.from("session");

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const randomSessionId = (): Buffer => {
  const buf = Buffer.alloc(8);
  crypto.getRandomValues(buf);
  return buf;
};

const sha256 = (input: Buffer): Buffer => createHash("sha256").update(input).digest();

const mintCommitment = (mints: PublicKey[]): Buffer => {
  // Same canonicalisation the frontend uses: sorted base58 strings, concatenated, then sha256.
  const sorted = [...mints].map((m) => m.toBase58()).sort();
  return sha256(Buffer.from(sorted.join("")));
};

const fundedKeypair = async (provider: anchor.AnchorProvider, lamports = LAMPORTS_PER_SOL): Promise<Keypair> => {
  const kp = Keypair.generate();
  const sig = await provider.connection.requestAirdrop(kp.publicKey, lamports);
  await provider.connection.confirmTransaction(sig, "confirmed");
  return kp;
};

const deriveSessionPda = (programId: PublicKey, sessionId: Buffer): [PublicKey, number] =>
  PublicKey.findProgramAddressSync([SESSION_SEED, sessionId], programId);

describe("silent_circle", () => {
  // Configure the client to use the cluster set in Anchor.toml.
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = new Program<SilentCircle>(idl, provider);

  // Cached test fixtures (one fresh session per test).
  let walletA: Keypair;
  let walletB: Keypair;

  before(async () => {
    walletA = await fundedKeypair(provider);
    walletB = await fundedKeypair(provider);
  });

  // ─────────────────────────────────────────────────────────────────────────
  // create_session
  // ─────────────────────────────────────────────────────────────────────────
  describe("create_session", () => {
    it("creates a session PDA with AwaitingCounterparty state", async () => {
      const sessionId = randomSessionId();
      const [sessionPda] = deriveSessionPda(program.programId, sessionId);
      const commitmentA = mintCommitment([Keypair.generate().publicKey, Keypair.generate().publicKey]);
      const expiresAt = new BN(Math.floor(Date.now() / 1000) + 24 * 60 * 60);

      await program.methods
        .createSession(Array.from(sessionId), Array.from(commitmentA), 0b111, expiresAt)
        .accounts({
          signer: walletA.publicKey,
          session: sessionPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([walletA])
        .rpc();

      const account = await program.account.session.fetch(sessionPda);

      expect(account.walletA.toBase58()).to.equal(walletA.publicKey.toBase58());
      expect(account.walletB.toBase58()).to.equal(PublicKey.default.toBase58());
      expect(Buffer.from(account.commitmentA).equals(commitmentA)).to.equal(true);
      expect(account.assetMask).to.equal(0b111);
      assert.deepEqual(account.state, { awaitingCounterparty: {} });
      expect(account.intersection).to.have.lengthOf(0);
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // commit_set
  // ─────────────────────────────────────────────────────────────────────────
  describe("commit_set", () => {
    it("lets wallet B join and transitions state to BothCommitted", async () => {
      const sessionId = randomSessionId();
      const [sessionPda] = deriveSessionPda(program.programId, sessionId);
      const expiresAt = new BN(Math.floor(Date.now() / 1000) + 3600);

      await program.methods
        .createSession(Array.from(sessionId), Array.from(mintCommitment([])), 0b001, expiresAt)
        .accounts({ signer: walletA.publicKey, session: sessionPda, systemProgram: SystemProgram.programId })
        .signers([walletA])
        .rpc();

      const commitmentB = mintCommitment([Keypair.generate().publicKey]);

      await program.methods
        .commitSet(Array.from(commitmentB))
        .accounts({ signer: walletB.publicKey, session: sessionPda })
        .signers([walletB])
        .rpc();

      const account = await program.account.session.fetch(sessionPda);
      expect(account.walletB.toBase58()).to.equal(walletB.publicKey.toBase58());
      expect(Buffer.from(account.commitmentB).equals(commitmentB)).to.equal(true);
      assert.deepEqual(account.state, { bothCommitted: {} });
    });

    it("rejects a second join attempt", async () => {
      const sessionId = randomSessionId();
      const [sessionPda] = deriveSessionPda(program.programId, sessionId);
      const expiresAt = new BN(Math.floor(Date.now() / 1000) + 3600);
      const walletC = await fundedKeypair(provider, 0.5 * LAMPORTS_PER_SOL);

      await program.methods
        .createSession(Array.from(sessionId), Array.from(mintCommitment([])), 0b001, expiresAt)
        .accounts({ signer: walletA.publicKey, session: sessionPda, systemProgram: SystemProgram.programId })
        .signers([walletA])
        .rpc();

      await program.methods
        .commitSet(Array.from(mintCommitment([])))
        .accounts({ signer: walletB.publicKey, session: sessionPda })
        .signers([walletB])
        .rpc();

      try {
        await program.methods
          .commitSet(Array.from(mintCommitment([])))
          .accounts({ signer: walletC.publicKey, session: sessionPda })
          .signers([walletC])
          .rpc();
        assert.fail("Expected commit_set to reject the second join.");
      } catch (err: any) {
        const log = (err.logs ?? []).join("\n");
        expect(log + (err.message ?? "")).to.match(/InvalidState|AlreadyJoined/);
      }
    });

    it("rejects commit_set after the session has expired", async () => {
      const sessionId = randomSessionId();
      const [sessionPda] = deriveSessionPda(program.programId, sessionId);
      // Already in the past — clock will reject immediately.
      const expiresAt = new BN(Math.floor(Date.now() / 1000) - 60);

      await program.methods
        .createSession(Array.from(sessionId), Array.from(mintCommitment([])), 0b001, expiresAt)
        .accounts({ signer: walletA.publicKey, session: sessionPda, systemProgram: SystemProgram.programId })
        .signers([walletA])
        .rpc();

      try {
        await program.methods
          .commitSet(Array.from(mintCommitment([])))
          .accounts({ signer: walletB.publicKey, session: sessionPda })
          .signers([walletB])
          .rpc();
        assert.fail("Expected commit_set to reject an expired session.");
      } catch (err: any) {
        const log = (err.logs ?? []).join("\n");
        expect(log + (err.message ?? "")).to.match(/SessionExpired/);
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // write_intersection — only the Arcium MXE callback may invoke it
  // ─────────────────────────────────────────────────────────────────────────
  describe("write_intersection", () => {
    it("rejects callers other than the Arcium program", async () => {
      const sessionId = randomSessionId();
      const [sessionPda] = deriveSessionPda(program.programId, sessionId);
      const expiresAt = new BN(Math.floor(Date.now() / 1000) + 3600);

      // Set up a session ready for callback testing (state irrelevant — the
      // signature/signer check fails first regardless of state).
      await program.methods
        .createSession(Array.from(sessionId), Array.from(mintCommitment([])), 0b001, expiresAt)
        .accounts({ signer: walletA.publicKey, session: sessionPda, systemProgram: SystemProgram.programId })
        .signers([walletA])
        .rpc();

      const attacker = await fundedKeypair(provider, 0.5 * LAMPORTS_PER_SOL);

      try {
        // We can't easily forge a SignedComputationOutputs<ComputePsiOutput>,
        // so we simply attempt to invoke the callback method as a regular
        // signer. The Arcium-supplied account constraints will reject it.
        await (program.methods as any)
          .writeIntersection({ field0: [new BN(0), new BN(0), new BN(0), new BN(0)] })
          .accounts({
            session: sessionPda,
            // Deliberately wrong: an attacker as the "callback caller".
            arciumProgram: attacker.publicKey,
          })
          .signers([attacker])
          .rpc();
        assert.fail("Expected write_intersection to reject a non-Arcium caller.");
      } catch (err: any) {
        // The exact error string varies (account constraint, signer mismatch,
        // signature verification) — anything that isn't a successful tx is fine.
        expect(err).to.exist;
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // close_session
  // ─────────────────────────────────────────────────────────────────────────
  describe("close_session", () => {
    it("rejects close while the session is still active", async () => {
      const sessionId = randomSessionId();
      const [sessionPda] = deriveSessionPda(program.programId, sessionId);
      const expiresAt = new BN(Math.floor(Date.now() / 1000) + 3600);

      await program.methods
        .createSession(Array.from(sessionId), Array.from(mintCommitment([])), 0b001, expiresAt)
        .accounts({ signer: walletA.publicKey, session: sessionPda, systemProgram: SystemProgram.programId })
        .signers([walletA])
        .rpc();

      try {
        await program.methods
          .closeSession()
          .accounts({ signer: walletA.publicKey, session: sessionPda, walletA: walletA.publicKey })
          .signers([walletA])
          .rpc();
        assert.fail("Expected close_session to reject an active session.");
      } catch (err: any) {
        const log = (err.logs ?? []).join("\n");
        expect(log + (err.message ?? "")).to.match(/SessionStillActive/);
      }
    });

    it("rejects close from a non-initiator", async () => {
      const sessionId = randomSessionId();
      const [sessionPda] = deriveSessionPda(program.programId, sessionId);
      const expiresAt = new BN(Math.floor(Date.now() / 1000) - 60);

      await program.methods
        .createSession(Array.from(sessionId), Array.from(mintCommitment([])), 0b001, expiresAt)
        .accounts({ signer: walletA.publicKey, session: sessionPda, systemProgram: SystemProgram.programId })
        .signers([walletA])
        .rpc();

      try {
        await program.methods
          .closeSession()
          .accounts({ signer: walletB.publicKey, session: sessionPda, walletA: walletA.publicKey })
          .signers([walletB])
          .rpc();
        assert.fail("Expected close_session to reject a non-initiator.");
      } catch (err: any) {
        // Either the has_one constraint (UnauthorizedClose) or the signer
        // mismatch — both block the unauthorised close.
        expect(err).to.exist;
      }
    });

    it("closes an expired session and refunds rent to wallet A", async () => {
      const sessionId = randomSessionId();
      const [sessionPda] = deriveSessionPda(program.programId, sessionId);
      const expiresAt = new BN(Math.floor(Date.now() / 1000) - 60);

      await program.methods
        .createSession(Array.from(sessionId), Array.from(mintCommitment([])), 0b001, expiresAt)
        .accounts({ signer: walletA.publicKey, session: sessionPda, systemProgram: SystemProgram.programId })
        .signers([walletA])
        .rpc();

      const balanceBefore = await provider.connection.getBalance(walletA.publicKey);

      await program.methods
        .closeSession()
        .accounts({ signer: walletA.publicKey, session: sessionPda, walletA: walletA.publicKey })
        .signers([walletA])
        .rpc();

      const balanceAfter = await provider.connection.getBalance(walletA.publicKey);
      const accountInfo = await provider.connection.getAccountInfo(sessionPda);

      expect(accountInfo).to.equal(null, "session PDA should be closed");
      expect(balanceAfter).to.be.greaterThan(balanceBefore, "rent should refund to wallet A");

      // Tiny pause to keep the validator state reads orderly across tests on
      // a slow devnet — harmless on localnet.
      await sleep(50);
    });
  });
});
